image_width: 1920
image_height: 1080
fov_h: 87.7
fov_v: 56.7 
usb_frame_rate: 60
usb_exposure: 500 # 1-80000
usb_gamma_: 160
usb_gain_: 10 # 0-96

y_left_odom_in_map: 0.55
y_right_odom_in_map: -0.65

z_cam2map: 0.42
white_height: 0
weight_height: 0.055
tall_wood_height: 0.2
short_wood_height: 0.1

x_left_gripper_offset: -0.01
x_right_gripper_offset: 0.01

y_left_get_offset: 0.02
y_right_get_offset: -0.06

y_left_put_offset: 0.03
y_right_put_offset: -0.055

max_match_error: 0.2
