image_width: 1920
image_height: 1080
fov_h: 87.7
fov_v: 56.7 
usb_frame_rate: 60
usb_exposure: 500 # 1-80000
usb_gamma_: 160
usb_gain_: 10 # 0-96

x_cam2gripper: -0.02
y_cam2gripper: 0.03
judge_distance: 0.15

t_odo2map_x0: 0.001
t_odo2map_y0: 0.001
state_cov0: 0.025
process_noise: 0.01
measurement_noise: 0.05

safe_height: -0.1
crawl_height: -0.234
short_place_height: 0.25
tall_place_height: 0.3

weights_height: 0.365 # 相机坐标系下(单位m)
tall_wood_height: 0.22
white_height: 0.42