image_width: 1920
image_height: 1080
fov_h: 87.7
fov_v: 56.7 
usb_frame_rate: 60
usb_exposure: 500 # 1-80000
usb_gamma_: 160
usb_gain_: 10 # 0-96

y_left_odom_in_map: 0.55
y_right_odom_in_map: -0.65

z_cam2map: 0.42
white_height: 0
weight_height: 0.055
tall_wood_height: 0.2
short_wood_height: 0.1

x_weight_offset_left: -0.02
y_weight_offset_left: 0.02
x_weight_offset_right: 0.02
y_weight_offset_right: -0.05

max_match_error: 0.2
